### ISSUE TITLE
FastTunnel.Server reads the configuration file but starts with the default settings

### ISSUE THREAD

**Issue by aacoutinho** [SpringHgui/FastTunnel#44]
I have downloaded and extracted FastTunnel.Server.linux-x64.tar.gz (v2.1.1) file to run on the ubuntu 20.04 server (amd64) machine. 

Then, I changed the permission of the exec file (chmod +x FastTunnel.Server) and edited the following config file appsettings.json in the same directory of FastTunnel:

{
  "AllowedHosts": "\*",
  "EnableFileLog": false,
  "urls": "http://*:443",
  "FastTunnel": {
     "BasePort": 443,
     "WebDomain": "laboratory.ddns.net",
     "WebAllowAccessIps": [ ],
     "EnableForward": true,
     "Tokens": [ ]
    }
}

Then,  I exec the FastTunnel.Server in the ubuntu server (amd64), that shows: 

larsid@instance-1:~/FastTunnel.Server.linux-x64$ ./FastTunnel.Server
[23:25:56 INF] User profile is available. Using '/home/user/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[23:25:56 INF] Now listening on: http://[::]:1270
[23:25:56 INF] Application started. Press Ctrl+C to shut down.
[23:25:56 INF] Hosting environment: Production
[23:25:56 INF] Content root path: /home/user/FastTunnel.Server.linux-x64

And How you can see, the FastTunnel.Server reads the configuration file, but it starts with the default settings, and not with the settings defined in the config file.

**Comment by SpringHgui** [comment]
`appsettings.json` is in directory `config` , not in the root of FastTunnel.Server

**Comment by aacoutinho** [comment]
Oh... I'm an idiot. Thanks for your attention!
