### ISSUE TITLE
docker镜像springhgui/fasttunnel无法正常监听端口

### ISSUE THREAD

**Issue by draculakkk** [SpringHgui/FastTunnel#47]
按照帮助文档通过镜像springhgui/fasttunnel启动的容器publish的端口在linux下无效，appsetting.json加上urls节点也不行，现在只能从源代码重新打包镜像才可以正常启动监听

**Comment by SpringHgui** [comment]
确实存在这个问题，镜像donet版本问题，运行失败了，后面有空修复
