### ISSUE TITLE
Ver 2.1.1 ARM64平台上不能正常正运作 

### ISSUE THREAD

**Issue by zlaimw** [SpringHgui/FastTunnel#48]
SpringHgui 您好，
我将你的FastTunnel 2.1.1 用docker buildx 命令生产 Linux/arm64 平台的镜像，成功启动了容器， 但运作时有日志报错：
       [10:31:15 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
       [10:31:15 INF] User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
      2[10:31:16 INF] Now listening on: http://[::]:1270
       [10:31:16 INF] Creating key {a6a83795-00ce-49a0-aa75-dd09d6be8975} with creation date 2022-07-23 10:31:16Z, activation date 2022-07-23 10:31:16Z, and expiration date 2022-10-21 10:31:16Z.
       [10:31:16 WRN] No XML encryptor configured. Key {a6a83795-00ce-49a0-aa75-dd09d6be8975} may be persisted to storage in unencrypted form.
      v[10:31:16 INF] Writing data to file '/root/.aspnet/DataProtection-Keys/key-a6a83795-00ce-49a0-aa75-dd09d6be8975.xml'.
      ?[10:31:16 INF] Application started. Press Ctrl+C to shut down.
      /[10:31:16 INF] Hosting environment: Production
      '[10:31:16 INF] Content root path: /app
      M[10:31:26 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      M[10:31:26 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      I[10:31:26 INF] 客户端连接 ::ffff:42.200.214.109 当前在线数：2
      I[10:31:26 INF] 客户端连接 ::ffff:42.200.214.109 当前在线数：2
      U[10:31:32 INF] 【0.0.0.0:1274】Accepted. There are 1 clients connected to the port
      o[10:31:32 INF] Request starting HTTP/1.1 PROXY http://laimw.ddns.net:1270/3714a2fdedfe4de29dc879f5ef543284 - -
      [10:31:32 ERR] 
      CSystem.Threading.Tasks.TaskCanceledException: A task was canceled.
          at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.Handle(HttpContext context, Func`1 next) in /src/FastTunnel.Core/Forwarder/MiddleWare/FastTunnelSwapHandler.cs:line 73
       [10:31:32 INF] Request finished HTTP/1.1 PROXY http://laimw.ddns.net:1270/3714a2fdedfe4de29dc879f5ef543284 - - - 200 0 - 250.3935ms
      U[10:31:36 INF] 【0.0.0.0:1274】Accepted. There are 2 clients connected to the port
      o[10:31:36 INF] Request starting HTTP/1.1 PROXY http://laimw.ddns.net:1270/912455a3017f497ebf16076b6e4a294f - -
      M[10:31:37 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      a[10:31:37 INF] Request finished HTTP/1.1 GET http://laimw.ddns.net:1270/ - - - 101 - - 38.2212ms
      M[10:31:47 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      a[10:31:47 INF] Request finished HTTP/1.1 GET http://laimw.ddns.net:1270/ - - - 101 - - 17.9902ms
      [10:31:55 ERR] 
      CSystem.Threading.Tasks.TaskCanceledException: A task was canceled.
          at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.Handle(HttpContext context, Func`1 next) in /src/FastTunnel.Core/Forwarder/MiddleWare/FastTunnelSwapHandler.cs:line 73
       [10:31:55 INF] Request finished HTTP/1.1 PROXY http://laimw.ddns.net:1270/912455a3017f497ebf16076b6e4a294f - - - 200 0 - 19663.7099ms
      M[10:31:57 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      a[10:31:58 INF] Request finished HTTP/1.1 GET http://laimw.ddns.net:1270/ - - - 101 - - 11.3246ms
      M[10:32:08 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      a[10:32:08 INF] Request finished HTTP/1.1 GET http://laimw.ddns.net:1270/ - - - 101 - - 11.3320ms
      M[10:32:18 INF] Request starting HTTP/1.1 GET http://laimw.ddns.net:1270/ - -
      a[10:32:18 INF] Request finished HTTP/1.1 GET http://laimw.ddns.net:1270/ - - - 101 - - 10.4260ms

请帮忙解决问题，谢谢！

**Comment by SpringHgui** [comment]
看着正常，是什么问题

**Comment by zlaimw** [comment]
不能成功联上RDP。请查看日志错误信息，有劳。谢谢。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpringHgui** [comment]
你端口开了吗，docker端口以及你云服务器端口

**Comment by zlaimw** [comment]
开了1270-1275端口。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpringHgui** [comment]
docker端口有没有和本地绑定

**Comment by zlaimw** [comment]
这个没有，我先研究一下，有问题再请教。感谢回复。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zlaimw** [comment]
经查，docker端口有和本地绑定，可成功telnet 1270,1271等。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpringHgui** [comment]
检查电脑是否开启了允许被远程，telnet 3389是否可连接

**Comment by zlaimw** [comment]
我用Windows平台测试过是可以的，用Docker可以联通一半，可看见远程的Windows画面，之后就断开了。说明网络、端口都没问题....我怀疑Docker arm64平台与应用有不兼容，具体日志上有报错的，有劳您研究一下以上日志。拜托。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpringHgui** [comment]
这可能是FastTunnel版本问题，有个旧版本存在自动断开连接这个问题

**Comment by zlaimw** [comment]
我是下载2.1.1 source code 来创建镜像的。可否提供可用版本的source code？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpringHgui** [comment]
2.1.1应该没这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月25日(星期一) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FastTunnel/FastTunnel] Ver 2.1.1 ARM64平台上不能正常正运作  (Issue #48)





 我是下载2.1.1 source code 来创建镜像的。可否提供可用版本的source code？ 
 
 获取Outlook for Android<https://aka.ms/AAb9ysg&gt; 
 ________________________________

**Comment by zlaimw** [comment]
您好！ 问题已解决了！ 还是Ver 2.1.1版本，我用docker build --platform linux/arm64...命令取代docker buildx build --platform linux/arm64... 重新创建镜像及启动容器后，应用运作正常。 感谢您的指导！！ 另， Ver 3.0.0-beta2 不支持创建linux/arm64 平台的docker镜像。

**Comment by zlaimw** [comment]
您好！问题已解决了。还是2.1.1版本，我用docker build --platform linux/arm64 .... 代替 docker buildx build --platform linux/arm64 ..... 重新创建镜像重新启动容器后应用运作正常了！感谢指导！   另，v3.0.0-beta2 不能创建arm64平台的docker 镜像。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
