### ISSUE TITLE
通过fastTunnel架设SVN内网穿透，上传带中文路径或者中文名称的文件时，报502错误

### ISSUE THREAD

**Issue by zhao-yc** [SpringHgui/FastTunnel#51]
![微信截图_20221014134353](https://user-images.githubusercontent.com/43179751/195771145-3d19daaa-4b9c-4216-92e7-c49e312a13e8.png)

**Comment by zhao-yc** [comment]
![微信截图_20221014135011](https://user-images.githubusercontent.com/43179751/195772245-3f42181e-a79e-4035-b6d0-3aef7b9d3160.png)
服务端报错如图

**Comment by SpringHgui** [comment]
aspnetcore不支持header中包含非ascii字符，目前无法解决，可以改用Forward模式走tcp协议试试

**Comment by zhao-yc** [comment]
感谢大神及时回复，改用Forward已解决该问题。

**Comment by zhao-yc** [comment]
感谢大神及时回复，改用Forward已解决该问题。
