### ISSUE TITLE
本质上是纯服务器转发?

### ISSUE THREAD

**Issue by sgf** [SpringHgui/FastTunnel#70]
我尝试搭建了一下.发现怎么感觉就是个服务器转发,我本来以为是p2p的.
举个例子:
公网s:111.111.111.111
家里client1:111.111.111.112 暴露3389到1274
公司:访问111.111.111.111:1274

首先公司不能通过自己跑client直连家里的client1
然后公司只能通过111.111.111.111:1274 访问家里的3389
所以本质上流量都走了服务端? 😂

**Comment by yangjieshao** [comment]
不然嘞？

**Comment by sgf** [comment]
> 不然嘞？

这么说确实是咯?  如果只是纯服务器转发的话,写这一大堆代码搞这么大一个工程量,其实没必要.😂

**Comment by sgf** [comment]
> 不然嘞？
这么说确实是咯?  如果只是纯服务器转发的话,写这一大堆代码搞这么大一个工程量,其实没必要.😂

**Comment by SpringHgui** [comment]
怎么不写代码，实现同样的功能 @sgf

**Comment by sgf** [comment]
> 怎么不写代码，实现同样的功能 @sgf

在写了,先抄个纯C#的2d图形库. 后面有空就着手了. RelayServer只是p2p的一个中转功能罢了.
