### ISSUE TITLE
程序支持绑定多个域名访问内网服务应该如何设置呢?

### ISSUE THREAD

**Issue by NOnamedcy** [SpringHgui/FastTunnel#76]

**Comment by SpringHgui** [comment]
多配置几个SubDomain都指向同一个服务即可
```
 "Webs": [
      {
        "LocalIp": "127.0.0.1",
        "LocalPort": 8090,
        "SubDomain": "test"
      },
      {
        "LocalIp": "127.0.0.1",
        "LocalPort": 8090,
        "SubDomain": "test1"
      },     
     {
        "LocalIp": "127.0.0.1",
        "LocalPort": 8090,
        "SubDomain": "test2"
      }
    ],
```

**Comment by NOnamedcy** [comment]
非常感谢

**Comment by NOnamedcy** [comment]
> 多配置几个SubDomain都指向同一个服务即可
> 
> ```
>  "Webs": [
>       {
>         "LocalIp": "127.0.0.1",
>         "LocalPort": 8090,
>         "SubDomain": "test"
>       },
>       {
>         "LocalIp": "127.0.0.1",
>         "LocalPort": 8090,
>         "SubDomain": "test1"
>       },     
>      {
>         "LocalIp": "127.0.0.1",
>         "LocalPort": 8090,
>         "SubDomain": "test2"
>       }
>     ],
> ```

我想修改指定多个WebDomain可以嘛？

**Comment by SpringHgui** [comment]
> > 多配置几个SubDomain都指向同一个服务即可
> > ```
> >  "Webs": [
> >       {
> >         "LocalIp": "127.0.0.1",
> >         "LocalPort": 8090,
> >         "SubDomain": "test"
> >       },
> >       {
> >         "LocalIp": "127.0.0.1",
> >         "LocalPort": 8090,
> >         "SubDomain": "test1"
> >       },     
> >      {
> >         "LocalIp": "127.0.0.1",
> >         "LocalPort": 8090,
> >         "SubDomain": "test2"
> >       }
> >     ],
> > ```
> 
> 我想修改指定多个WebDomain可以嘛？

多配置一条就行的话，就没太大的必要支持SubDomain指定多个子域名
