### ISSUE TITLE
网址完全挂了？suidao.io

### ISSUE THREAD

**Issue by kiinoo** [SpringHgui/FastTunnel#77]
访问suidao.io，如图
![image](https://github.com/user-attachments/assets/6b6054dd-a0d3-454f-ad53-bc6935d64d1c)

**Comment by SpringHgui** [comment]
是的域名没有再续费了

**Comment by yangjieshao** [comment]
> 是的域名没有再续费了

那 赶紧更新readme呀

**Comment by SpringHgui** [comment]
感谢提醒，已更新

**Comment by yangjieshao** [comment]
完事了 把issues 关掉啊 - -
