### ISSUE TITLE
FastTunnel.Client.exe  文件没有找到。。。。

### ISSUE THREAD

**Issue by hoheyho** [SpringHgui/FastTunnel#9]
FastTunnel.Client.exe  文件没有找到。。。。

**Comment by SpringHgui** [comment]
如果自己搭建服务，程序安装包在 [release](https://github.com/SpringHgui/FastTunnel/releases)下面
如果想快速体验内网穿透服务，直接去[演示站点](https://suidao.io)注册一下使用即可，比较简单
